services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: costaruan/app:latest
    container_name: app
    restart: always
    tty: true
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network-app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: costaruan/db:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    ports:
      - "3306:3306"
    networks:
      - network-app
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "--user=root",
          "--password=root",
          "ping",
          "-h",
          "db",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - network-app

networks:
  network-app:
    driver: bridge